### ISSUE TITLE
[BUG]: Cannot add shim with spaces in path

### ISSUE THREAD

**Issue by WoMspace** [ScoopInstaller/Shim#6] opened 2023-07-03 10:11 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

shim

### Expected/Current Behaviour

Attempting to add a custom shim with spaces in the path name.
### I try:
`scoop shim add blender "C:\Program Files (x86)\Steam\steamapps\common\Blender\blender.exe"`
### I expect:
Added shim
### I get:
`ERROR: Command path does not exist: C:\Program`

### Steps to Reproduce

```console
Have a binary installed to a path that contains a space, in my case, Blender via steam.
PS> scoop shim add blender "C:\Program Files (x86)\Steam\steamapps\common\Blender\blender.exe"
```

### Possible Solution

I suspect the parsing for the shim path doesn't take quotes into account. I tried with single quotes, double quotes, and various methods of escaping spaces

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
de518b81b (HEAD -> master, origin/master, origin/HEAD) xmrig: Update to version 6.20.0

'java' bucket:
3be07903 (HEAD -> master, origin/master, origin/HEAD) temurin11-nightly-jre: Update to version 11.0.20-7.0.202307011715

'main' bucket:
a7d80ade4 (HEAD -> master, origin/master, origin/HEAD) memcached: Update to version 1.6.21

'nerd-fonts' bucket:
176a44f (HEAD -> master, origin/master, origin/HEAD) LXGWNeoXiHei: Update to version 1.102.1
```

### Scoop Config

```console
last_update        scoop_branch scoop_repo
-----------        ------------ ----------
3/7/23 11:00:12 AM master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Additional Softwares

Steam

**Comment by HUMORCE** [comment] 2023-07-03 11:25
It's bug in Scoop core.

Duplicate of https://github.com/ScoopInstaller/Scoop/issues/5313

**Comment by WoMspace** [comment] 2023-07-03 11:26
ah cool thanks

**Closed as completed by HUMORCE** 2023-07-03 11:25 UTC
Labels: bug
